# Generated by Django 4.2.3 on 2023-07-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_blog', models.CharField(max_length=20)),
                ('nombre_autor', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('apellido_autor', models.CharField(max_length=20)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
