# Generated by Django 4.2.3 on 2023-07-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_albun_albunimagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albunimagen',
            name='albun',
        ),
        migrations.DeleteModel(
            name='Albun',
        ),
        migrations.DeleteModel(
            name='AlbunImagen',
        ),
    ]
