# Generated by Django 4.2.3 on 2023-07-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
