# Generated by Django 4.2.3 on 2023-07-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_delete_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/imagenes')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=500, null=True)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.blog')),
            ],
        ),
    ]
