# Generated by Django 4.2.3 on 2023-07-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
