# Generated by Django 4.2.3 on 2023-07-22 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_albun_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='albun',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Albun',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
