# Generated by Django 4.2.3 on 2023-07-22 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.blog'),
        ),
    ]
