# Generated by Django 4.2.3 on 2023-07-22 10:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0014_alter_imagen_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='descripcion',
            field=ckeditor.fields.RichTextField(max_length=800, null=True),
        ),
    ]
