# Generated by Django 4.2.3 on 2023-07-26 23:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0017_remove_imagen_albun_remove_imagen_blog_delete_albun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_blog', models.CharField(max_length=20)),
                ('nombre_autor', models.CharField(max_length=20)),
                ('apellido_autor', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=100, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/imagenes')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', ckeditor.fields.RichTextField(max_length=800, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('albun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.albun')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.blog')),
            ],
        ),
        migrations.AddField(
            model_name='albun',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.blog'),
        ),
    ]
