# Generated by Django 4.2.3 on 2023-07-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0018_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categoria',
            field=models.CharField(choices=[('IL', 'Ilustración'), ('FT', 'Fotografía'), ('AT', 'Arte Tradicional'), ('3D', 'Diseño 3D')], max_length=2),
        ),
    ]
