# Generated by Django 4.2.3 on 2023-08-10 23:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_infoextra_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoextra',
            name='biografia',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
